{
 "title": "Observabilidade .NET 10",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requisições por Segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{application=\"my-api-dotnet\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs em Tempo Real",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"my-api-dotnet\"} |= ``"
    }
   ]
  },
  {
   "title": "Query para CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query para Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}